# Generated by Django 5.1.2 on 2025-01-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('book_type', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
